version: '3'
services: 
  web: 
    build: app

    ports: 
      - '5000:5000'

    environment:
      # FLASK_ENV: development
      FLASK_DEBUG: "true"
    
    env_file:
      - .env

    volumes:
      - ./app:/app